In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
ds = pd.read_csv('car_dataset.csv')

x = ds[['year','present_price','driven_kms']]
y = ds['fuel_type']


ds.head(5)

,year,present_price,driven_kms,fuel_type,transmission,selling_price,owner
0,2011,23.94,147469,1,1,14.576084,0
1,2019,5.11,63072,1,1,3.546387,0
2,2015,13.13,93820,1,0,10.777211,0
3,2012,8.21,33284,0,0,6.656172,0
4,2011,14.42,93369,1,0,6.940395,0

In [ ]:
# sns.pairplot(data = ds, hue='fuel_type')


ds.drop(['transmission'], axis = 1, inplace=True)
ds.drop(['present_price'], axis = 1, inplace = True)

ds.columns.unique
ds.head(5)

   year  driven_kms  fuel_type  selling_price  owner
0  2011      147469          1      14.576084      0
1  2019       63072          1       3.546387      0
2  2015       93820          1      10.777211      0
3  2012       33284          0       6.656172      0
4  2011       93369          1       6.940395      0

In [ ]:
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.preprocessing import StandardScaler , OneHotEncoder 
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# OVR

In [ ]:
x_train, x_test,y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

lo = LogisticRegression(multi_class='ovr')
lo.fit(x_train,y_train)

lo.score(x_test, y_test)*100

d:\python\Machine_Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(

80.0

In [ ]:
lo1 = LogisticRegression()
lo1.fit(x_train, y_train)
lo1.score(x_test,y_test)*100

80.0